"""kernel initial schema

Every kernel table (sessions/messages/events) carries a required
``user_id`` (owner id) plus a matching ``ix_<table>_user_id`` index, stamped from
``src.core.owner_context`` (host-seeded at boot). Regenerated as the single
baseline; existing kernel DBs are wiped + rebuilt by
``boot.kernel.drop_stale_kernel_tables`` (``user_id`` fingerprint) per the
dev-stage no-data-preservation policy.

Revision ID: 0001
Revises:
Create Date: 2026-06-09 02:53:14.558789

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_events_message_id", ["message_id"], unique=False)
        batch_op.create_index(
            "ix_events_session_timestamp", ["session_id", "timestamp"], unique=False
        )
        batch_op.create_index("ix_events_session_type", ["session_id", "type"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_message", sa.JSON(), nullable=False),
        sa.Column("assistant_message", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stop_reason", sa.JSON(), nullable=True),
        sa.Column("total_turns", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=True),
        sa.Column("model_usage", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.BigInteger(), nullable=False),
        sa.Column("ended_at", sa.BigInteger(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("todos", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'errored', 'cancelled')", name="ck_messages_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_session_started", ["session_id", "started_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_messages_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("agent_config", sa.JSON(), nullable=False),
        sa.Column("cwd", sa.Text(), nullable=False),
        sa.Column("runtime_provider", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("mcp_servers", sa.JSON(), nullable=False),
        sa.Column("model_provider", sa.JSON(), nullable=True),
        sa.Column("model_settings", sa.JSON(), nullable=True),
        sa.Column("permission_mode", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stop_reason", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("runtime_session_id", sa.String(length=64), nullable=True),
        sa.Column("todos", sa.JSON(), nullable=True),
        sa.CheckConstraint("mode IN ('default', 'plan', 'goal')", name="ck_sessions_mode"),
        sa.CheckConstraint(
            "permission_mode IN ('default', 'auto_review', 'full_access')",
            name="ck_sessions_permission_mode",
        ),
        sa.CheckConstraint(
            "runtime_provider IN ('claude_agent', 'codex', 'deepagents')",
            name="ck_sessions_runtime_provider",
        ),
        sa.CheckConstraint(
            "status IN ('created', 'idle', 'running', 'terminated')", name="ck_sessions_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_sessions_status", ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index("ix_sessions_status")
        batch_op.drop_index("ix_sessions_created_at")

    op.drop_table("sessions")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_user_id"))
        batch_op.drop_index("ix_messages_session_started")

    op.drop_table("messages")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_user_id"))
        batch_op.drop_index("ix_events_session_type")
        batch_op.drop_index("ix_events_session_timestamp")
        batch_op.drop_index("ix_events_message_id")

    op.drop_table("events")
    # ### end Alembic commands ###
