import type { DesktopRouteModule } from "../profile";

export const personalDesktopRoutes: DesktopRouteModule[] = [
  {
    id: "conversations-home",
    path: "/",
    label: "nav.home",
    description: "Recent chats, drafts, and local session entrypoints.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "conversation-detail",
    path: "/conversation/:id",
    label: "nav.chat",
    description: "Active conversation with tool calls and streaming output.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "projects",
    path: "/projects",
    label: "sidebar.projects",
    description: "Project lists with files, notes, and scoped agent context.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "project-detail",
    path: "/projects/:id",
    label: "route.projectDetail",
    description: "Files, knowledge, and conversations scoped to one project.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "knowledge",
    path: "/knowledge",
    label: "nav.knowledge",
    description: "Imported documents and local knowledge collections.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "agents",
    path: "/agents",
    label: "nav.agents",
    description: "Official agents available to instantiate.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "agent-detail",
    path: "/agents/:slug",
    label: "route.agentDetail",
    description: "Read-only agent view and instantiation into a project.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "task-detail",
    path: "/tasks/:taskId",
    label: "task.detailTitle",
    description: "Lead-dispatch task timeline, runs, and interventions.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "skills",
    path: "/skills",
    label: "sidebar.skills",
    description: "Official and custom skills available to the local agent.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "marketplace",
    path: "/marketplace",
    label: "nav.marketplace",
    description: "Discover and import agents, teams, and skills.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "skill-detail",
    path: "/skills/:skillId",
    label: "route.skillDetail",
    description: "Detailed view and editing of a skill.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "connectors",
    path: "/connectors",
    label: "nav.connectors",
    description: "Data connectors and MCP integrations available to the agent.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "plugins",
    path: "/plugins",
    label: "plugin.title",
    description:
      "Installed Agent Plugins (skill suites and skills + connectors bundles).",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "settings",
    path: "/settings",
    label: "nav.settings",
    description: "Models, credentials, and local desktop preferences.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "component-gallery",
    path: "/developer/components",
    label: "route.componentGallery",
    description: "Shared component catalog with distribution extension groups.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "onboarding",
    path: "/onboarding",
    label: "route.onboarding",
    description: "First-run experience for new desktop users.",
    layout: "standalone",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "first-launch",
    path: "/welcome",
    label: "onboarding.welcome",
    description: "Connection selector for first-time setup.",
    layout: "standalone",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "api-key-config",
    path: "/auth/api-key",
    label: "route.apiKeyConfig",
    description: "Manual API key configuration.",
    layout: "standalone",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "tool-calls",
    path: "/tool-calls",
    label: "route.toolCalls",
    description: "Prototype gallery for tool invocation states.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "context-panel",
    path: "/context-panel",
    label: "route.contextPanel",
    description: "Right-rail examples for chat and project context.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "overlays",
    path: "/overlays",
    label: "route.overlays",
    description: "Prototype command palette and confirmation surfaces.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "playbooks",
    path: "/playbooks",
    label: "playbook.title",
    description: "Reusable versioned executable prompts and their runs.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "automation",
    path: "/automations",
    label: "automation.title",
    description: "Recurring agent runs (cron + interval triggers).",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "automation-detail",
    path: "/automations/:automationId",
    label: "route.automationDetail",
    description: "Automation detail view with execution log.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "activity",
    path: "/activity",
    label: "nav.activity",
    description: "Overview of running (and recently finished) runs.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
];
