import type { DesktopRouteModule } from "../profile";

export const personalDesktopRoutes: DesktopRouteModule[] = [
  {
    id: "conversations-home",
    path: "/",
    label: "nav.home",
    description: "Recent chats, drafts, and local session entrypoints.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "conversation-detail",
    path: "/conversation/:id",
    label: "Conversation",
    description: "Active conversation with tool calls and streaming output.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "projects",
    path: "/projects",
    label: "Projects",
    description: "Project lists with files, notes, and scoped agent context.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "project-detail",
    path: "/projects/:id",
    label: "Project Detail",
    description: "Files, knowledge, and conversations scoped to one project.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "knowledge",
    path: "/knowledge",
    label: "Knowledge",
    description: "Imported documents and local knowledge collections.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "agents",
    path: "/agents",
    label: "Agents",
    description: "Official agents available to instantiate.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "agent-detail",
    path: "/agents/:slug",
    label: "Agent Detail",
    description: "Read-only agent view and instantiation into a project.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "task-detail",
    path: "/tasks/:taskId",
    label: "Task Detail",
    description: "Lead-dispatch task timeline, runs, and interventions.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "skills",
    path: "/skills",
    label: "Skills",
    description: "Official and custom skills available to the local agent.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "skill-detail",
    path: "/skills/:skillId",
    label: "Skill Detail",
    description: "Detailed view and editing of a skill.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "connectors",
    path: "/connectors",
    label: "nav.connectors",
    description: "Data connectors and MCP integrations available to the agent.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "settings",
    path: "/settings",
    label: "Settings",
    description: "Models, credentials, and local desktop preferences.",
    layout: "project",
    showInNav: true,
    edition: "personal",
  },
  {
    id: "onboarding",
    path: "/onboarding",
    label: "Onboarding",
    description: "First-run experience for new desktop users.",
    layout: "standalone",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "first-launch",
    path: "/welcome",
    label: "Welcome",
    description: "Connection selector for first-time setup.",
    layout: "standalone",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "api-key-config",
    path: "/auth/api-key",
    label: "API Key Config",
    description: "Manual API key configuration.",
    layout: "standalone",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "tool-calls",
    path: "/tool-calls",
    label: "Tool Calls",
    description: "Prototype gallery for tool invocation states.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "context-panel",
    path: "/context-panel",
    label: "Context Panel",
    description: "Right-rail examples for chat and project context.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "overlays",
    path: "/overlays",
    label: "Overlays",
    description: "Prototype command palette and confirmation surfaces.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "automation",
    path: "/automations",
    label: "Automation",
    description: "Recurring agent runs (cron + interval triggers).",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
  {
    id: "activity",
    path: "/activity",
    label: "Activity",
    description: "Overview of running (and recently finished) runs.",
    layout: "project",
    showInNav: false,
    edition: "personal",
  },
];
