import {
  DESKTOP_CAPABILITIES_CHANNEL,
  NETWORK_EGRESS_CHANNELS,
  NETWORK_EGRESS_EVENTS,
} from "@valuz/desktop-network-egress/contracts";

export const DESKTOP_CHANNELS = {
  getServicesStatus: "get_services_status",
  startAllServices: "start_all_services",
  stopAllServices: "stop_all_services",
  restartService: "restart_service",
  getServiceLogs: "get_service_logs",
  getAgentServerInfo: "get_agent_server_info",
  getShellStatus: "desktop_shell_status",
  listServiceDescriptors: "list_service_descriptors",
  registerServiceDescriptor: "register_service_descriptor",
  unregisterServiceDescriptor: "unregister_service_descriptor",
  desktopGetCapabilities: DESKTOP_CAPABILITIES_CHANNEL,
  egressGetDiagnostics: NETWORK_EGRESS_CHANNELS.getDiagnostics,
  egressGetSnapshots: NETWORK_EGRESS_CHANNELS.getSnapshots,
  egressGetMode: NETWORK_EGRESS_CHANNELS.getMode,
  egressGetStatus: NETWORK_EGRESS_CHANNELS.getStatus,
  egressGetRuntimePhases: NETWORK_EGRESS_CHANNELS.getRuntimePhases,
  egressSetMode: NETWORK_EGRESS_CHANNELS.setMode,
  selectDirectory: "select_directory",
  openExternalUrl: "open_external_url",
  appGetVersion: "app_get_version",
  appQuit: "app_quit",
  appRelaunch: "app_relaunch",
  windowOpenNew: "window_open_new",
  windowMinimize: "window_minimize",
  windowMaximize: "window_maximize",
  windowClose: "window_close",
  windowIsMaximized: "window_is_maximized",
  windowReload: "window_reload",
  windowToggleDevTools: "window_toggle_devtools",
  windowToggleFullscreen: "window_toggle_fullscreen",
  cliLoginStatus: "cli_login_status",
  cliLoginLaunch: "cli_login_launch",
  cliInstallStatus: "cli_install_status",
  cliInstallToPath: "cli_install_to_path",
  cliUninstallFromPath: "cli_uninstall_from_path",
  updaterCheck: "updater:check",
  updaterDownload: "updater:download",
  updaterQuitAndInstall: "updater:quit-and-install",
  updaterShowWindow: "updater:show-window",
  updaterGetState: "updater:get-state",
  setMenuLocale: "set_menu_locale",
  // Desktop notification bridge (task attention & reliability).
  notify: "desktop_notify",
  setBadgeCount: "desktop_set_badge_count",
  bounce: "desktop_bounce",
} as const;

export const DESKTOP_EVENTS = {
  serviceStatusChanged: "service-status-changed",
  serviceDescriptorsChanged: "service-descriptors-changed",
  egressStatusChanged: NETWORK_EGRESS_EVENTS.statusChanged,
  updaterChecking: "updater:checking",
  updaterAvailable: "updater:available",
  updaterNotAvailable: "updater:not-available",
  updaterProgress: "updater:progress",
  updaterDownloaded: "updater:downloaded",
  updaterError: "updater:error",
  // Fired when the user clicks a native notification — payload carries the
  // in-app route the renderer should navigate to.
  notificationClicked: "notification-clicked",
} as const;
