"""initial schema

Every business table carries a required ``user_id`` (the owner id) plus a
matching ``ix_<table>_user_id`` index. The column is stamped from the
request-scoped owner ContextVar (``infra.owner_context``); in OSS that resolves
to the device-derived local install id, under the commercial overlay to the
logged-in user.

Pre-release the host chain is kept as this **single baseline**: schema changes
fold into it rather than accumulating incremental revisions (clean-up policy —
nothing is shipped yet). Folded so far: ``0002_add_skill_origin``,
``0002_null_subscription_model_snapshots`` (its seeder-side semantics live in
code), the de-projectize chain (``valuz_project_session`` index table in, the
two ``kernel_agent_id`` columns out). Existing dev DBs — including ones stamped
with a folded revision id — are wiped + rebuilt by
``boot.schema.drop_stale_host_tables`` per the dev-stage no-data-preservation
policy.

Revision ID: 0001
Revises:
Create Date: 2026-06-09 02:48:34.560156

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "valuz_agent",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("runtime", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("connector_types", sa.JSON(), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=True),
        sa.Column("effort", sa.String(length=16), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("readonly", sa.Boolean(), nullable=False),
        sa.Column("deletable", sa.Boolean(), nullable=False),
        sa.Column("avatar", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("valuz_agent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_agent_user_id"), ["user_id"], unique=False)

    op.create_table(
        "valuz_app_setting",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("valuz_app_setting", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_app_setting_user_id"), ["user_id"], unique=False)

    op.create_table(
        "valuz_automation",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("agent_kind", sa.String(length=32), nullable=False),
        sa.Column("agent_slug", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("action_kind", sa.String(length=16), nullable=False),
        sa.Column("trigger_kind", sa.String(length=32), nullable=False),
        sa.Column("cron_expr", sa.String(length=128), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("next_run_at", sa.BigInteger(), nullable=True),
        sa.Column("last_run_at", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "(trigger_kind = 'cron' AND cron_expr IS NOT NULL) OR trigger_kind != 'cron'",
            name="ck_automation_cron_expr_when_cron",
        ),
        sa.CheckConstraint(
            "(trigger_kind = 'interval' AND interval_seconds IS NOT NULL "
            "AND interval_seconds >= 30) OR trigger_kind != 'interval'",
            name="ck_automation_interval_seconds_floor",
        ),
        sa.CheckConstraint("action_kind IN ('chat', 'task')", name="ck_automation_action_kind"),
        sa.CheckConstraint(
            "agent_kind IN ('project_member', 'library_agent')", name="ck_automation_agent_kind"
        ),
        sa.CheckConstraint(
            "trigger_kind IN ('cron', 'interval', 'manual')", name="ck_automation_trigger_kind"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_automation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_automation_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_valuz_automation_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "valuz_automation_run",
        sa.Column("automation_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("triggered_at", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.BigInteger(), nullable=True),
        sa.Column("completed_at", sa.BigInteger(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("created_files", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_automation_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_automation_run_automation_id"), ["automation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_valuz_automation_run_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "valuz_connector",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("connector_type", sa.String(length=32), nullable=False),
        sa.Column("transport", sa.String(length=16), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("auth_type", sa.String(length=32), nullable=False),
        sa.Column("oauth_metadata_json", sa.Text(), nullable=True),
        sa.Column("oauth_client_info_json", sa.Text(), nullable=True),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("args_json", sa.Text(), nullable=True),
        sa.Column("working_dir", sa.Text(), nullable=True),
        sa.Column("env_json", sa.Text(), nullable=True),
        sa.Column("headers_json", sa.Text(), nullable=True),
        sa.Column("params_json", sa.Text(), nullable=True),
        sa.Column("cred_manifest_json", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("tool_count", sa.Integer(), nullable=True),
        sa.Column("last_tested_at", sa.BigInteger(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "auth_type IN ('none', 'bearer', 'oauth')", name="ck_valuz_connector_auth_type"
        ),
        sa.CheckConstraint(
            "transport IN ('http', 'sse', 'stdio')", name="ck_valuz_connector_transport"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("valuz_connector", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_connector_user_id"), ["user_id"], unique=False)

    op.create_table(
        "valuz_document_import_task",
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("kb_id", sa.String(length=36), nullable=True),
        sa.Column("source_label", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("processed_items", sa.Integer(), nullable=False),
        sa.Column("failed_items", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("errors_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_document_import_task", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_document_import_task_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "valuz_document_record",
        sa.Column("kb_id", sa.String(length=36), nullable=False),
        sa.Column("kb_folder_id", sa.String(length=36), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("source_filename", sa.String(length=512), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("discovery_source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("preview_text_path", sa.Text(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("parser_mode", sa.String(length=32), nullable=True),
        sa.Column("docs_runtime_id", sa.String(length=64), nullable=True),
        sa.Column("runtime_doc_ref", sa.String(length=256), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("parser_attempts_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_document_record", schema=None) as batch_op:
        batch_op.create_index("ix_doc_kb_folder", ["kb_id", "kb_folder_id"], unique=False)
        batch_op.create_index("ix_doc_status", ["kb_id", "status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_valuz_document_record_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index("ux_doc_relative_path", ["kb_id", "relative_path"], unique=True)

    op.create_table(
        "valuz_kb_folder",
        sa.Column("kb_id", sa.String(length=36), nullable=False),
        sa.Column("parent_folder_id", sa.String(length=36), nullable=True),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("descendant_document_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_kb_folder", schema=None) as batch_op:
        batch_op.create_index("ix_kb_folder_kb_parent", ["kb_id", "parent_folder_id"], unique=False)
        batch_op.create_index("ix_kb_folder_status", ["kb_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_valuz_kb_folder_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ux_kb_folder_path", ["kb_id", "relative_path"], unique=True)

    op.create_table(
        "valuz_knowledge_base",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("root_path", sa.Text(), nullable=False),
        sa.Column("parser_routing", sa.String(length=32), nullable=False),
        sa.Column("auto_discover", sa.Boolean(), nullable=False),
        sa.Column("last_full_scan_at", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_knowledge_base", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_knowledge_base_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index("ux_kb_root_path", ["root_path"], unique=True)

    op.create_table(
        "valuz_onboarding_state",
        sa.Column("step_id", sa.String(length=64), nullable=False),
        sa.Column("seen", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("step_id"),
    )
    with op.batch_alter_table("valuz_onboarding_state", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_onboarding_state_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "valuz_polling_task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("external_task_id", sa.String(length=128), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("next_poll_at", sa.BigInteger(), nullable=True),
        sa.Column("result_json", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_polling_task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_polling_task_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_valuz_polling_task_next_poll_at"), ["next_poll_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_valuz_polling_task_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_valuz_polling_task_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "valuz_project_kb_binding",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("binding_kind", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("project_id", "binding_kind", "target_id"),
    )
    with op.batch_alter_table("valuz_project_kb_binding", schema=None) as batch_op:
        batch_op.create_index("ix_binding_project", ["project_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_valuz_project_kb_binding_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "valuz_project_member",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("agent_slug", sa.String(length=128), nullable=False),
        sa.Column("source_agent_slug", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "agent_slug", name="uq_project_member_ws_slug"),
    )
    with op.batch_alter_table("valuz_project_member", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_project_member_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_valuz_project_member_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "valuz_project_session",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_project_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_project_session_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_valuz_project_session_session_id"), ["session_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_valuz_project_session_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "valuz_project_skill_config",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("skill_path", sa.Text(), nullable=False),
        sa.Column("added_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("project_id", "skill_path"),
    )
    with op.batch_alter_table("valuz_project_skill_config", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_project_skill_config_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "valuz_provider",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("provider_kind", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("credential_source", sa.String(length=32), nullable=False),
        sa.Column("account_provider_id", sa.String(length=64), nullable=True),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("default_model", sa.String(length=128), nullable=True),
        sa.Column("model_ids", sa.Text(), nullable=True),
        sa.Column("secret_ref", sa.String(length=256), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("deletable", sa.Boolean(), nullable=False),
        sa.Column("test_status", sa.String(length=32), nullable=False),
        sa.Column("test_error", sa.Text(), nullable=True),
        sa.Column("tested_at", sa.BigInteger(), nullable=True),
        sa.Column("protocol", sa.String(length=32), nullable=True),
        sa.Column("auth_type", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_provider", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_provider_user_id"), ["user_id"], unique=False)

    op.create_table(
        "valuz_session_attachment",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("parse_mode", sa.String(length=32), nullable=True),
        sa.Column("parsed_path", sa.Text(), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("source_kb_id", sa.String(length=36), nullable=True),
        sa.Column("source_kb_doc_id", sa.String(length=36), nullable=True),
        sa.Column("consumed_at", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_session_attachment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_session_attachment_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_valuz_session_attachment_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "valuz_setup_job",
        sa.Column("setup_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("downloaded_bytes", sa.Integer(), nullable=False),
        sa.Column("total_bytes", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=256), nullable=True),
        sa.Column("started_at", sa.BigInteger(), nullable=True),
        sa.Column("completed_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("setup_id"),
    )
    with op.batch_alter_table("valuz_setup_job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_setup_job_user_id"), ["user_id"], unique=False)

    op.create_table(
        "valuz_shortcut_binding",
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("key_combo", sa.String(length=128), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("action_id"),
    )
    with op.batch_alter_table("valuz_shortcut_binding", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_shortcut_binding_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "valuz_skill_index",
        sa.Column("slug", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("project_root", sa.Text(), nullable=True),
        sa.Column("manifest_filename", sa.String(length=256), nullable=True),
        sa.Column("tags_json", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("readonly", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("folder_created_at", sa.BigInteger(), nullable=True),
        sa.Column("creation_origin", sa.String(length=32), nullable=True),
        sa.Column("origin_json", sa.Text(), nullable=True),
        sa.Column("deletable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_skill_index", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_skill_index_user_id"), ["user_id"], unique=False)

    op.create_table(
        "valuz_task",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=False),
        sa.Column("lead_agent_slug", sa.String(length=128), nullable=False),
        sa.Column("current_holder", sa.String(length=128), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("plan_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("committed_at", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_task_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_valuz_task_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "valuz_task_event",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "task_id", "sequence", name="uq_task_event_ws_task_seq"
        ),
    )
    with op.batch_alter_table("valuz_task_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_task_event_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_valuz_task_event_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_valuz_task_event_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "valuz_task_session",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("agent_slug", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("subtask_key", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("dispatched_by", sa.String(length=36), nullable=True),
        sa.Column("project_mode", sa.String(length=16), nullable=False),
        sa.Column("run_dir", sa.Text(), nullable=True),
        sa.Column("result_manifest", sa.JSON(), nullable=True),
        sa.Column("ended_at", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_task_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_valuz_task_session_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_valuz_task_session_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_valuz_task_session_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_valuz_task_session_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "valuz_project",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("root_path", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=16), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("instructions_md", sa.Text(), nullable=True),
        sa.Column("memory_summary", sa.Text(), nullable=True),
        sa.Column("memory_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valuz_project", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valuz_project_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("valuz_project", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_project_user_id"))

    op.drop_table("valuz_project")
    with op.batch_alter_table("valuz_task_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_task_session_project_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_task_session_user_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_task_session_task_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_task_session_session_id"))

    op.drop_table("valuz_task_session")
    with op.batch_alter_table("valuz_task_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_task_event_project_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_task_event_user_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_task_event_task_id"))

    op.drop_table("valuz_task_event")
    with op.batch_alter_table("valuz_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_task_project_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_task_user_id"))

    op.drop_table("valuz_task")
    with op.batch_alter_table("valuz_skill_index", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_skill_index_user_id"))

    op.drop_table("valuz_skill_index")
    with op.batch_alter_table("valuz_shortcut_binding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_shortcut_binding_user_id"))

    op.drop_table("valuz_shortcut_binding")
    with op.batch_alter_table("valuz_setup_job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_setup_job_user_id"))

    op.drop_table("valuz_setup_job")
    with op.batch_alter_table("valuz_session_attachment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_session_attachment_user_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_session_attachment_session_id"))

    op.drop_table("valuz_session_attachment")
    with op.batch_alter_table("valuz_provider", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_provider_user_id"))

    op.drop_table("valuz_provider")
    with op.batch_alter_table("valuz_project_skill_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_project_skill_config_user_id"))

    op.drop_table("valuz_project_skill_config")
    with op.batch_alter_table("valuz_project_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_project_session_user_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_project_session_session_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_project_session_project_id"))

    op.drop_table("valuz_project_session")
    with op.batch_alter_table("valuz_project_member", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_project_member_project_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_project_member_user_id"))

    op.drop_table("valuz_project_member")
    with op.batch_alter_table("valuz_project_kb_binding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_project_kb_binding_user_id"))
        batch_op.drop_index("ix_binding_project")

    op.drop_table("valuz_project_kb_binding")
    with op.batch_alter_table("valuz_polling_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_polling_task_user_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_polling_task_status"))
        batch_op.drop_index(batch_op.f("ix_valuz_polling_task_next_poll_at"))
        batch_op.drop_index(batch_op.f("ix_valuz_polling_task_kind"))

    op.drop_table("valuz_polling_task")
    with op.batch_alter_table("valuz_onboarding_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_onboarding_state_user_id"))

    op.drop_table("valuz_onboarding_state")
    with op.batch_alter_table("valuz_knowledge_base", schema=None) as batch_op:
        batch_op.drop_index("ux_kb_root_path")
        batch_op.drop_index(batch_op.f("ix_valuz_knowledge_base_user_id"))

    op.drop_table("valuz_knowledge_base")
    with op.batch_alter_table("valuz_kb_folder", schema=None) as batch_op:
        batch_op.drop_index("ux_kb_folder_path")
        batch_op.drop_index(batch_op.f("ix_valuz_kb_folder_user_id"))
        batch_op.drop_index("ix_kb_folder_status")
        batch_op.drop_index("ix_kb_folder_kb_parent")

    op.drop_table("valuz_kb_folder")
    with op.batch_alter_table("valuz_document_record", schema=None) as batch_op:
        batch_op.drop_index("ux_doc_relative_path")
        batch_op.drop_index(batch_op.f("ix_valuz_document_record_user_id"))
        batch_op.drop_index("ix_doc_status")
        batch_op.drop_index("ix_doc_kb_folder")

    op.drop_table("valuz_document_record")
    with op.batch_alter_table("valuz_document_import_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_document_import_task_user_id"))

    op.drop_table("valuz_document_import_task")
    with op.batch_alter_table("valuz_connector", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_connector_user_id"))

    op.drop_table("valuz_connector")
    with op.batch_alter_table("valuz_automation_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_automation_run_user_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_automation_run_automation_id"))

    op.drop_table("valuz_automation_run")
    with op.batch_alter_table("valuz_automation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_automation_project_id"))
        batch_op.drop_index(batch_op.f("ix_valuz_automation_user_id"))

    op.drop_table("valuz_automation")
    with op.batch_alter_table("valuz_app_setting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_app_setting_user_id"))

    op.drop_table("valuz_app_setting")
    with op.batch_alter_table("valuz_agent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valuz_agent_user_id"))

    op.drop_table("valuz_agent")
    # ### end Alembic commands ###
