"""Generate TypeScript and Python type definitions from i18n locale files.

Usage:
    cd backend && uv run python ../i18n/scripts/gen_types.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from check_keys import _collect_dot_paths, _repo_root

_TS_HEADER = "// Auto-generated by i18n/scripts/gen_types.py — DO NOT EDIT.\n// Regenerate with: make i18n-gen\n\n"

_PY_HEADER = '"""Auto-generated by i18n/scripts/gen_types.py — DO NOT EDIT.\n\nRegenerate with: make i18n-gen\n"""\n\n'


def _format_union(keys: list[str], quote: str, indent: str) -> str:
    return "\n".join(f"{indent}{quote}{k}{quote}," for k in keys)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    repo = _repo_root()
    ref_path = repo / "i18n" / "locales" / "en-US.json"
    if not ref_path.is_file():
        print(f"ERROR: reference locale not found: {ref_path}", file=sys.stderr)
        return 1

    keys = sorted(_collect_dot_paths(json.loads(ref_path.read_text(encoding="utf-8"))))
    if not keys:
        print("ERROR: en-US.json has no translation keys", file=sys.stderr)
        return 1

    # TypeScript
    #
    # We emit two type aliases:
    #
    #   KnownI18nKey — the closed union of all keys present in the main
    #                  ``i18n/locales/en-US.json`` file. Used for keys
    #                  that go through the codegen pipeline (everything
    #                  the main app owns).
    #
    #   I18nKey      — ``KnownI18nKey | (string & {})``. The branded
    #                  string keeps TypeScript autocomplete on known
    #                  keys but lets plugin-owned keys (registered via
    #                  ``registerLocaleNamespace`` at runtime) flow
    #                  through ``t()`` without a type error.
    ts_path = repo / "frontend" / "packages" / "shared" / "src" / "types" / "i18n.ts"
    ts_body = "\n".join(f'  | "{k}"' for k in keys)
    ts_content = (
        f"{_TS_HEADER}"
        f'/** Dot-path translation keys from i18n/locales/en-US.json. */\n'
        f"export type KnownI18nKey =\n{ts_body};\n\n"
        f'/** Either a known main-app key or a plugin-contributed key.\n'
        f' *  Plugin keys are registered at runtime via\n'
        f' *  ``registerLocaleNamespace`` and never go through codegen. */\n'
        f"export type I18nKey = KnownI18nKey | (string & {{}});\n"
    )
    _write(ts_path, ts_content)
    print(f"generated {ts_path.relative_to(repo)}")

    # Python keys
    py_keys_path = repo / "backend" / "valuz_agent" / "generated" / "i18n_keys.py"
    py_body = _format_union(keys, '"', "    ")
    py_content = (
        f"{_PY_HEADER}"
        f"from __future__ import annotations\n\nfrom typing import Literal\n\n"
        f"# fmt: off\nI18nKey = Literal[\n{py_body}\n]\n# fmt: on\n"
    )
    _write(py_keys_path, py_content)
    print(f"generated {py_keys_path.relative_to(repo)}")

    # Python __init__
    py_init = repo / "backend" / "valuz_agent" / "generated" / "__init__.py"
    py_init_content = f'{_PY_HEADER}from valuz_agent.generated.i18n_keys import I18nKey\n\n__all__ = ["I18nKey"]\n'
    _write(py_init, py_init_content)
    print(f"generated {py_init.relative_to(repo)}")

    print(f"\n{len(keys)} keys generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
